---
- hosts: complab
  become: yes
  tasks:
      - name: Reset ufw to default settings
        ufw: state=reset

      - name: Enable ufw and allow ssh traffic
        ufw: state=enabled rule=allow name=OpenSSH

      - name: Update and upgrade apt packages
        apt: update_cache=yes upgrade=safe

      - name: Harden server with common packages
        apt: state=present name={{ item }}
        with_items:
            - fail2ban
